name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  python_build:
    name: Build web files
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        run: python ./src/build.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Webcontent
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: web-updates
          delete-branch: true
          title: '[Webcontent] Update Webcontent'
          body: |
            Automated deployment
            - Changes made by the CI
            - to be deployed at [docs.dyren.de][1]

            [1]: https://docs.dyren.de/
          labels: |
            automated
            gh-pages
          assignees: max-42
          reviewers: max-42
          team-reviewers: |
            owners
            maintainers
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        
      - name: Cleanup
        run: |
          rm -R ./.git
          rm -R ./.github
          rm -R ./src
          rm ./README.md
          rm ./requirements.txt
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: /home/runner/work/dyrendocs/dyrendocs
    

  docker_build:
    
    name: Build and upload docker image
    needs: python_build

    runs-on: ubuntu-latest

    steps:
    
    - name: Download required files
      uses: actions/download-artifact@v2
      with:
        name: files
        path: /home/runner/work/dyrendocs/dyrendocs
        
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Build the image
      run: docker build -t docker.pkg.github.com/dyren-de/dyrendocs/dyrendocs:1.1 .

    - name: Save the image
      run: docker save docker.pkg.github.com/dyren-de/dyrendocs/dyrendocs:1.1 | gzip > dyrendocs.tar.gz

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: image
        path: dyrendocs.tar.gz
