name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin    
      
    - name: Build the image
      run: docker build -t docker.pkg.github.com/dyren-de/dyrendocs/dyrendocs:1.0 .
      
    - name: Push the image
      run: docker push docker.pkg.github.com/dyren-de/dyrendocs/dyrendocs:1.0
